### ISSUE TITLE
Geojson Point Type Request (Edit: Alias Request)

### ISSUE THREAD

**Issue by dougbutner** [pinknetworkx/atomicassets-contract#40]
I want to request a new type of `Point` in the specification that follows the rfc 7946 standard

Simply [43.356, 24.456]

> see: https://geojson.org/

The use case is for geo-dapps (like cXc.world) This allows people to attach geographic information to NFTs, and opens up the possibility to filter by proximity (in Postgres its STDistance function) and also further geopolitical information (Nation, slosest city, etc) can be extrapolated from this information which may be useful to dapps in the future. 

Personally, I don't think this should be an option on the site for everyone, but it could be. You could even allow people to pick this point on a map. 

Perhaps it doesn't seem like this is a "sought-after" use case, but I believe we're moving towards more geo-aware dapps in the future, so could be a first-mover advantage.

**Comment by dougbutner** [comment]
Also, I recommend using wgs84 srid 4326

**Comment by dougbutner** [comment]
I see now, after looking at these

> 'int8', 'int16', 'int32', 'int64', 'uint8', 'uint16', 'uint32', 'uint64', 'float32', 'float64', 'string', 'INT8_VEC', 'INT16_VEC', 'INT32_VEC', 'INT64_VEC', 'UINT8_VEC', 'UINT16_VEC', 'UINT32_VEC', 'UINT64_VEC', 'FLOAT_VEC', 'DOUBLE_VEC', 'STRING_VEC'

 that it may not make sense to add a whole new type, but may be better to allow `point` to be passed as an alias for `DOUBLE_VEC` or `FLOAT_VEC`

**Comment by jona-wilmsmann** [comment]
Refer to #39 for a detailed response. This would be another example of a media type that could potentially be supported.
